### ISSUE TITLE
Re-assistir aula

### ISSUE THREAD

**Issue by Muciojaziel** [Muciojaziel/quero-aulas#17]
Nesse caso, 
- deve ser possivel o aluno solicitar a aula novamente? 
- Ou deveria ser possivel o professor solicitar pq recebeu um rankeamento abaixo do que ele esperava, então no caso, o professor teria a chance de "redimir" sua aula, lecionando novamente e buscar um melhor pontuação com o aluno?

**Comment by gcsgivanildo** [comment]
No caso poderia ser uma aula para tirardúvidas

**Comment by Muciojaziel** [comment]
Certo, talvez não tenha deixado claro, digo, se o aluno já teve a aula pra tirar sua dúvida e não gostou? Rankeou o professor com nota baixa! O que deveria acontecer?
